name: Periodic Health Check

on:
  push:
  schedule:
    - cron: '0 6 * * *'

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Health check
        uses: Jtalk/url-health-check-action@v3
        with:
          url: https://your-deployment-url.com/health
          follow-redirect: true
          max-attempts: 3
          retry-delay: 5s
