# .github/workflows/deploy.yml
name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: always()  # Se ejecuta siempre, incluso si falla el build

    steps:
      - name: Send Discord notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: >
            ${{ job.status == 'success' &&
              ':white_check_mark: Deployment successful! :rocket:' ||
              ':x: Deployment failed!\nCommit: `${{ github.sha }}`\nMessage: `${{ github.event.head_commit.message }}`\nAuthor: `${{ github.event.head_commit.author.name }}`'
            }}
